# Generated by Django 2.0.1 on 2018-11-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logoimg', models.ImageField(blank=True, default='', upload_to='logotype/photos', verbose_name='логотип')),
            ],
            options={
                'verbose_name': 'логотип',
                'verbose_name_plural': 'лого',
            },
        ),
    ]
