# Generated by Django 2.0.1 on 2018-11-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('privet', models.CharField(max_length=30, verbose_name='приветствие')),
                ('description', models.TextField(verbose_name='описание')),
                ('photo', models.ImageField(blank=True, default='', upload_to='mainpage/photos', verbose_name='фотография')),
            ],
            options={
                'verbose_name': 'главная',
                'verbose_name_plural': 'главная',
            },
        ),
    ]
